services:
  postgres_db:
    image: postgres:16.1
    container_name: db_postgres_fairqueues
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - path: ./database.environment
        required: true